name: ai_chat_bot
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  equatable: ^2.0.8
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  flutter_svg: ^2.2.3
  device_info_plus: ^10.1.0
  image_picker: ^1.0.7
  record: ^4.4.4
  photo_manager: ^3.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  google_fonts: ^8.0.0
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - env/.env.dev
