name: ai_chat_bot
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  equatable: ^2.0.8
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - env/.env.dev
