name: ai_chat_bot
description: "Meh-GPT: The AI that tries... sometimes."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  equatable: ^2.0.8
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  flutter_svg: ^2.2.3
  skeletonizer: ^2.0.0
  device_info_plus: ^12.3.0
  gal: ^2.3.0
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.5
  pasteboard: ^0.4.0
  mime: ^2.0.0
  photo_manager: ^3.0.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  google_fonts: ^8.0.0
  flutter_markdown: ^0.7.7+1
  flutter_highlighter: ^0.1.1
  animated_text_kit: ^4.2.2
  markdown: ^7.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^12.0.1
  fl_chart: ^1.1.1
  flutter_colorpicker: ^1.0.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - env/.env.dev
    - assets/icons/
